language: python
python:
  - "2.7"
  - "3.6"
os: linux
dist: trusty
install:
  - pip install coveralls
script: nosetests --with-coverage --cover-package=calc --cover-erase
after_success:
  - coveralls
